import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Footer from "@/lib/components/footer/footer";
import NavbarTop from "@/lib/components/navbar-top/navbar-top";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative">
          <NavbarTop />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
